"""empty message

Revision ID: 96d7bd43cddb
Revises: 4eba84077ba4
Create Date: 2021-03-30 23:29:54.955765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d7bd43cddb'
down_revision = '4eba84077ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('done', table_name='todo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('done', 'todo', ['done'], unique=True)
    # ### end Alembic commands ###
